services:
  backend:
    build:
      context: ./backend
      dockerfile: lmapp/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your-secret-api-key
      - PYTHONPATH=/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: lmapp/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
